from pathlib import Path
p=Path('bibleapp/app/src/main/java/com/biblequest/pro/MainActivity.kt')
s=p.read_text()
s=s.replace('import androidx.activity.compose.setContent\n','import androidx.activity.compose.setContent\nimport androidx.activity.compose.BackHandler\n')
old='''@Composable fun BibleQuestProV2(){\n    var page by remember{mutableStateOf(Page.HOME)}\n    var lang by remember{mutableStateOf(BibleData.languages.first())}\n    var player by remember{mutableStateOf(Player())}\n    var selectedBook by remember{mutableStateOf(BibleData.books.first())}\n    var selectedChapter by remember{mutableIntStateOf(1)}'''
new='''@Composable fun BibleQuestProV2(){\n    val context=LocalContext.current\n    val prefs=remember{context.getSharedPreferences("bible_quest_v24",android.content.Context.MODE_PRIVATE)}\n    val savedLang=prefs.getString("lang","en-GB") ?: "en-GB"\n    var page by remember{mutableStateOf(runCatching{Page.valueOf(prefs.getString("page",Page.HOME.name)!!)}.getOrDefault(Page.HOME))}\n    var lang by remember{mutableStateOf(BibleData.languages.firstOrNull{it.code==savedLang} ?: BibleData.languages.first())}\n    var player by remember{mutableStateOf(Player())}\n    var selectedBook by remember{mutableStateOf(BibleData.books.firstOrNull{it.number==prefs.getInt("book",1)} ?: BibleData.books.first())}\n    var selectedChapter by remember{mutableIntStateOf(prefs.getInt("chapter",1).coerceAtLeast(1))}\n    var resumeIndex by remember{mutableIntStateOf(prefs.getInt("quiz_index",0).coerceAtLeast(0))}\n    var resumeScore by remember{mutableIntStateOf(prefs.getInt("quiz_score",0).coerceAtLeast(0))}'''
assert old in s
s=s.replace(old,new,1)
s=s.replace('    var curatedQuestions by remember{mutableStateOf(emptyList<CuratedQ>())}', '    var curatedQuestions by remember{mutableStateOf(if(page==Page.CURATED){ val c=prefs.getInt("curated_count",10).coerceIn(1,50); BibleData.curated.let{src->if(c<=src.size)src.take(c) else List(c){src[it%src.size]}} }else emptyList<CuratedQ>())}',1)
s=s.replace('curatedQuestions=BibleData.curated.shuffled().let { src ->\n                if(count<=src.size)src.take(count) else List(count){src[it%src.size]}.shuffled()\n            }','curatedQuestions=BibleData.curated.let { src ->\n                if(count<=src.size)src.take(count) else List(count){src[it%src.size]}\n            }',1)
s=s.replace('''    val tone=remember{ToneGenerator(AudioManager.STREAM_MUSIC,55)}\n    val context=LocalContext.current\n    val bgm=''','''    val tone=remember{ToneGenerator(AudioManager.STREAM_MUSIC,55)}\n    val bgm=''',1)
s=s.replace('var music by remember{mutableStateOf(true)}','var music by remember{mutableStateOf(prefs.getBoolean("music",true))}',1)
s=s.replace('var musicVolume by remember{mutableFloatStateOf(.76f)}','var musicVolume by remember{mutableFloatStateOf(prefs.getFloat("music_volume",.88f).coerceIn(.15f,1f))}',1)
s=s.replace('var sfx by remember{mutableStateOf(true)}','var sfx by remember{mutableStateOf(prefs.getBoolean("sfx",true))}',1)
s=s.replace('var mixedCount by remember{mutableIntStateOf(10)}','var mixedCount by remember{mutableIntStateOf(prefs.getInt("mixed_count",10).coerceIn(10,50))}',1)
anchor='''    DisposableEffect(Unit){onDispose{tone.release();bgm.release()}}\n\n    fun startCurated(count:Int){'''
insert='''    DisposableEffect(Unit){onDispose{tone.release();bgm.release()}}\n    LaunchedEffect(page,lang.code,selectedBook.number,selectedChapter,mixedCount,music,musicVolume,sfx,resumeIndex,resumeScore){\n        prefs.edit().putString("page",page.name).putString("lang",lang.code).putInt("book",selectedBook.number)\n            .putInt("chapter",selectedChapter).putInt("mixed_count",mixedCount).putBoolean("music",music)\n            .putFloat("music_volume",musicVolume).putBoolean("sfx",sfx).putInt("quiz_index",resumeIndex)\n            .putInt("quiz_score",resumeScore).putInt("curated_count",curatedQuestions.size.coerceAtLeast(10)).apply()\n    }\n    BackHandler(enabled=page!=Page.HOME){\n        page=when(page){\n            Page.CHAPTER_QUIZ->Page.CHAPTERS\n            Page.CHAPTERS->Page.BOOKS\n            Page.BOOKS->Page.HOME\n            else->Page.HOME\n        }\n    }\n\n    fun startCurated(count:Int){'''
assert anchor in s
s=s.replace(anchor,insert,1)
s=s.replace('''    fun startCurated(count:Int){\n        if(lang.code=="en-GB" || lang.code=="hi-IN"){''','''    fun startCurated(count:Int){\n        resumeIndex=0; resumeScore=0\n        if(lang.code=="en-GB" || lang.code=="hi-IN"){''',1)
s=s.replace('{selectedChapter=it;page=Page.CHAPTER_QUIZ}','{selectedChapter=it;resumeIndex=0;resumeScore=0;page=Page.CHAPTER_QUIZ}',1)
s=s.replace('Page.CHAPTER_QUIZ->ChapterQuiz(lang,selectedBook,selectedChapter,repo,sfx,tone,{item->','Page.CHAPTER_QUIZ->ChapterQuiz(lang,selectedBook,selectedChapter,repo,sfx,tone,resumeIndex,resumeScore,{i,sc->resumeIndex=i;resumeScore=sc},{item->',1)
s=s.replace('Page.MIXED->MixedScriptureQuiz(lang,mixedCount,repo,sfx,tone,{item->','Page.MIXED->MixedScriptureQuiz(lang,mixedCount,repo,sfx,tone,resumeIndex,resumeScore,{i,sc->resumeIndex=i;resumeScore=sc},{item->',1)
s=s.replace('Page.CURATED->CuratedQuiz(lang,curatedQuestions,sfx,tone,{q->','Page.CURATED->CuratedQuiz(lang,curatedQuestions,sfx,tone,resumeIndex,resumeScore,{i,sc->resumeIndex=i;resumeScore=sc},{q->',1)
s=s.replace('''                    autoScore=score\n                    resultTotal=total''','''                    autoScore=score\n                    resumeIndex=0;resumeScore=0\n                    resultTotal=total''',2)
s=s.replace('''                    curatedScore=score\n                    resultTotal=total''','''                    curatedScore=score\n                    resumeIndex=0;resumeScore=0\n                    resultTotal=total''',1)
s=s.replace('''    l:Lang,count:Int,repo:ScriptureRepository,sfx:Boolean,tone:ToneGenerator,\n    onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit''','''    l:Lang,count:Int,repo:ScriptureRepository,sfx:Boolean,tone:ToneGenerator,\n    initialIndex:Int,initialScore:Int,onProgress:(Int,Int)->Unit,\n    onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit''',1)
s=s.replace('else->AutoQuizBody(l,qs,sfx,tone,onWrong,onFinish)','else->AutoQuizBody(l,qs,sfx,tone,initialIndex,initialScore,onProgress,onWrong,onFinish)',1)
s=s.replace('''@Composable private fun ChapterQuiz(l:Lang,book:BookInfo,chapter:Int,repo:ScriptureRepository,sfx:Boolean,tone:ToneGenerator,onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit){''','''@Composable private fun ChapterQuiz(l:Lang,book:BookInfo,chapter:Int,repo:ScriptureRepository,sfx:Boolean,tone:ToneGenerator,initialIndex:Int,initialScore:Int,onProgress:(Int,Int)->Unit,onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit){''',1)
s=s.replace('else->AutoQuizBody(l,qs,sfx,tone,onWrong,onFinish)','else->AutoQuizBody(l,qs,sfx,tone,initialIndex,initialScore,onProgress,onWrong,onFinish)',1)
old='''@Composable private fun AutoQuizBody(l:Lang,qs:List<AutoQ>,sfx:Boolean,tone:ToneGenerator,onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit){\n    var idx by remember{mutableIntStateOf(0)};var picked by remember(qs){mutableIntStateOf(-1)};var reveal by remember(qs){mutableStateOf(false)};var score by remember(qs){mutableIntStateOf(0)}'''
new='''@Composable private fun AutoQuizBody(l:Lang,qs:List<AutoQ>,sfx:Boolean,tone:ToneGenerator,initialIndex:Int,initialScore:Int,onProgress:(Int,Int)->Unit,onWrong:(WrongItem)->Unit,onFinish:(Int,Int)->Unit){\n    var idx by remember(qs){mutableIntStateOf(initialIndex.coerceIn(0,(qs.size-1).coerceAtLeast(0)))};var picked by remember(qs){mutableIntStateOf(-1)};var reveal by remember(qs){mutableStateOf(false)};var score by remember(qs){mutableIntStateOf(initialScore)}'''
assert old in s
s=s.replace(old,new,1)
s=s.replace('else{idx++;picked=-1;reveal=false}','else{idx++;picked=-1;reveal=false;onProgress(idx,score)}',1)
old='''@Composable private fun CuratedQuiz(l:Lang,qs:List<CuratedQ>,sfx:Boolean,tone:ToneGenerator,onWrong:(CuratedQ)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit){\n    if(qs.isEmpty()){LaunchedEffect(Unit){back()};return}\n    var idx by remember{mutableIntStateOf(0)};var picked by remember(qs){mutableIntStateOf(-1)};var reveal by remember(qs){mutableStateOf(false)};var score by remember(qs){mutableIntStateOf(0)}'''
new='''@Composable private fun CuratedQuiz(l:Lang,qs:List<CuratedQ>,sfx:Boolean,tone:ToneGenerator,initialIndex:Int,initialScore:Int,onProgress:(Int,Int)->Unit,onWrong:(CuratedQ)->Unit,onFinish:(Int,Int)->Unit,back:()->Unit){\n    if(qs.isEmpty()){LaunchedEffect(Unit){back()};return}\n    var idx by remember(qs){mutableIntStateOf(initialIndex.coerceIn(0,qs.lastIndex))};var picked by remember(qs){mutableIntStateOf(-1)};var reveal by remember(qs){mutableStateOf(false)};var score by remember(qs){mutableIntStateOf(initialScore)}'''
assert old in s
s=s.replace(old,new,1)
s=s.replace('else{idx++;picked=-1;reveal=false}})','else{idx++;picked=-1;reveal=false;onProgress(idx,score)}})',1)
p.write_text(s)
gp=Path('bibleapp/app/build.gradle.kts'); g=gp.read_text(); g=g.replace('versionCode = 3','versionCode = 4').replace('versionName = "2.3.0"','versionName = "2.4.0"'); gp.write_text(g)
print('v2.4 resume/back/audio patch applied')
