package com.boogie.quest.ui.components

import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.boogie.quest.model.PuzzleSpec
import com.boogie.quest.ui.theme.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.math.abs
import kotlin.random.Random

@Composable
fun PuzzleHost(puzzle: PuzzleSpec,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){when(puzzle){
is PuzzleSpec.Choice->ChoicePuzzle(puzzle,onAttempt,onCorrect,onWrong)
is PuzzleSpec.Input->InputPuzzle(puzzle,onAttempt,onCorrect,onWrong)
is PuzzleSpec.Memory->MemoryPuzzle(puzzle,onAttempt,onCorrect,onWrong)
is PuzzleSpec.TapOrder->TapOrderPuzzle(puzzle,onAttempt,onCorrect,onWrong)
is PuzzleSpec.Simon->SimonPuzzle(puzzle,onAttempt,onCorrect,onWrong)
is PuzzleSpec.Lights->LightsPuzzle(puzzle,onCorrect)
is PuzzleSpec.Slide->SlidePuzzle(puzzle,onCorrect)
is PuzzleSpec.GridPath->GridPathPuzzle(puzzle,onAttempt,onCorrect,onWrong)}}

@Composable private fun ChoicePuzzle(p:PuzzleSpec.Choice,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){var locked by remember(p){mutableStateOf(false)};var wrongIndex by remember(p){mutableIntStateOf(-1)};Column(verticalArrangement=Arrangement.spacedBy(11.dp)){p.options.forEachIndexed{index,label->val wrong=wrongIndex==index;val bg by animateColorAsState(if(wrong)Danger.copy(alpha=.15f) else Panel2,label="choice");Surface(Modifier.fillMaxWidth().clickable(enabled=!locked){onAttempt();if(index==p.answer){locked=true;onCorrect()}else{wrongIndex=index;onWrong()}},color=bg,shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,if(wrong)Danger.copy(alpha=.55f)else Color.White.copy(alpha=.08f))){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Surface(color=Rose.copy(alpha=.12f),shape=RoundedCornerShape(12.dp)){Text(('A'.code+index).toChar().toString(),Modifier.padding(horizontal=10.dp,vertical=6.dp),color=Blush,fontWeight=FontWeight.Black)};Spacer(Modifier.width(12.dp));Text(label,color=Ink,fontWeight=FontWeight.Bold)}}}}}

@Composable private fun InputPuzzle(p:PuzzleSpec.Input,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){var value by remember(p){mutableStateOf("")};var error by remember(p){mutableStateOf(false)};Column(horizontalAlignment=Alignment.CenterHorizontally){OutlinedTextField(value,onValueChange={if(it.length<=12){value=it;error=false}},singleLine=true,keyboardOptions=KeyboardOptions(keyboardType=if(p.keyboardNumeric)KeyboardType.Number else KeyboardType.Text),label={Text("Your answer")},isError=error,modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp));Spacer(Modifier.height(14.dp));GradientButton("CHECK ANSWER",onClick={if(value.isNotBlank()){onAttempt();if(value.trim().equals(p.answer.trim(),true))onCorrect()else{error=true;onWrong()}}},modifier=Modifier.fillMaxWidth());if(error){Spacer(Modifier.height(8.dp));Text("Not quite. Try another angle ♡",color=Danger,fontSize=12.sp)}}}

@Composable private fun MemoryPuzzle(p:PuzzleSpec.Memory,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){val deck=remember(p){(p.symbols+p.symbols).shuffled(Random(p.prompt.hashCode()))};var first by remember(p){mutableIntStateOf(-1)};var second by remember(p){mutableIntStateOf(-1)};var matched by remember(p){mutableStateOf(setOf<Int>())};var busy by remember(p){mutableStateOf(false)};val scope=rememberCoroutineScope();LazyVerticalGrid(GridCells.Fixed(4),Modifier.fillMaxWidth().height(if(deck.size<=8)190.dp else 290.dp),userScrollEnabled=false,horizontalArrangement=Arrangement.spacedBy(9.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){items(deck.size){idx->val revealed=idx==first||idx==second||idx in matched;Surface(Modifier.aspectRatio(1f).clickable(enabled=!busy&&!revealed){if(first<0)first=idx else{second=idx;busy=true;if(deck[first]==deck[idx]){val pair=setOf(first,idx);val n=matched+pair;matched=n;first=-1;second=-1;busy=false;if(n.size==deck.size)onCorrect()}else{onAttempt();onWrong();scope.launch{delay(620);first=-1;second=-1;busy=false}}}},color=if(idx in matched)Mint.copy(alpha=.12f)else if(revealed)Violet.copy(alpha=.20f)else Panel2,shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,if(idx in matched)Mint.copy(alpha=.45f)else Color.White.copy(alpha=.08f))){Box(contentAlignment=Alignment.Center){Text(if(revealed)deck[idx]else"•",fontSize=26.sp,color=if(revealed)Ink else Muted,fontWeight=FontWeight.Black)}}}};Spacer(Modifier.height(10.dp));Text("Matched ${matched.size/2} / ${deck.size/2}",color=Muted,fontSize=12.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())}

@Composable private fun TapOrderPuzzle(p:PuzzleSpec.TapOrder,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){val expected=remember(p){if(p.ascending)p.values.sorted()else p.values.sortedDescending()};var step by remember(p){mutableIntStateOf(0)};val clicked=remember(p){mutableStateListOf<Int>()};val cols=if(p.values.size>6)4 else 3;LazyVerticalGrid(GridCells.Fixed(cols),Modifier.fillMaxWidth().height(if(p.values.size>6)220.dp else 160.dp),userScrollEnabled=false,horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(p.values.size){idx->val v=p.values[idx];val done=v in clicked;Surface(Modifier.aspectRatio(1f).clickable(enabled=!done){if(v==expected[step]){clicked+=v;step++;if(step==expected.size)onCorrect()}else{onAttempt();onWrong()}},color=if(done)Mint.copy(alpha=.13f)else Panel2,shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,if(done)Mint.copy(alpha=.40f)else Color.White.copy(alpha=.08f))){Box(contentAlignment=Alignment.Center){Text(v.toString(),color=Ink,fontSize=20.sp,fontWeight=FontWeight.Black)}}}};Spacer(Modifier.height(10.dp));Text("${if(p.ascending)"LOW → HIGH"else"HIGH → LOW"} • $step/${expected.size}",color=Muted,fontSize=11.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())}

@Composable private fun SimonPuzzle(p:PuzzleSpec.Simon,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){var active by remember(p){mutableIntStateOf(-1)};var accepting by remember(p){mutableStateOf(false)};var step by remember(p){mutableIntStateOf(0)};var replay by remember(p){mutableIntStateOf(0)};val colors=listOf(Rose,Violet,Gold,Mint);LaunchedEffect(p,replay){accepting=false;step=0;delay(450);p.sequence.forEach{v->active=v;delay(360);active=-1;delay(120)};accepting=true};Column(horizontalAlignment=Alignment.CenterHorizontally){Text(if(accepting)"Your turn"else"Watch carefully…",color=if(accepting)Mint else Muted,fontWeight=FontWeight.Bold);Spacer(Modifier.height(14.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){repeat(p.paletteSize){idx->val lit=active==idx;val scale by animateFloatAsState(if(lit)1.08f else 1f,spring(dampingRatio=.55f),label="pad");Surface(Modifier.weight(1f).aspectRatio(1f).graphicsLayer(scaleX=scale,scaleY=scale).clickable(enabled=accepting){if(idx==p.sequence[step]){step++;if(step==p.sequence.size){accepting=false;onCorrect()}}else{onAttempt();onWrong();accepting=false;replay++}},color=colors[idx%colors.size].copy(alpha=if(lit).95f else .18f),shape=RoundedCornerShape(22.dp),border=BorderStroke(1.dp,colors[idx%colors.size].copy(alpha=.55f))){Box(contentAlignment=Alignment.Center){Text((idx+1).toString(),color=Ink,fontWeight=FontWeight.Black,fontSize=18.sp)}}}};Spacer(Modifier.height(14.dp));Text(if(accepting)"Progress $step / ${p.sequence.size}"else"Sequence length ${p.sequence.size}",color=Muted,fontSize=12.sp)}}

private fun toggle(board:MutableList<Boolean>,size:Int,index:Int){val r=index/size;val c=index%size;listOf(r to c,r-1 to c,r+1 to c,r to c-1,r to c+1).forEach{(rr,cc)->if(rr in 0 until size&&cc in 0 until size){val i=rr*size+cc;board[i]=!board[i]}}}
@Composable private fun LightsPuzzle(p:PuzzleSpec.Lights,onCorrect:()->Unit){val initial=remember(p){MutableList(p.size*p.size){false}.also{b->p.seedMoves.forEach{toggle(b,p.size,it)}}};val board=remember(p){mutableStateListOf<Boolean>().also{it.addAll(initial)}};var moves by remember(p){mutableIntStateOf(0)};LazyVerticalGrid(GridCells.Fixed(p.size),Modifier.fillMaxWidth().height(if(p.size==3)270.dp else 300.dp),userScrollEnabled=false,horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(board.size){idx->val on=board[idx];val glow by animateColorAsState(if(on)Gold else Panel2,label="light");Surface(Modifier.aspectRatio(1f).clickable{val copy=board.toMutableList();toggle(copy,p.size,idx);copy.forEachIndexed{i,v->board[i]=v};moves++;if(board.none{it})onCorrect()},color=glow.copy(alpha=if(on).82f else 1f),shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,if(on)Gold else Color.White.copy(alpha=.08f))){Box(contentAlignment=Alignment.Center){Text(if(on)"✦"else"·",color=if(on)Night else Muted,fontSize=24.sp,fontWeight=FontWeight.Black)}}}};Spacer(Modifier.height(8.dp));Text("MOVES $moves",color=Muted,fontSize=11.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())}

private fun scrambledTiles(size:Int,moves:Int,seed:Int):List<Int>{val a=(1 until size*size).toMutableList().apply{add(0)};var blank=a.lastIndex;val rnd=Random(seed);var previous=-1;repeat(moves){val r=blank/size;val c=blank%size;val candidates=mutableListOf<Int>();if(r>0)candidates+=blank-size;if(r<size-1)candidates+=blank+size;if(c>0)candidates+=blank-1;if(c<size-1)candidates+=blank+1;val options=candidates.filter{it!=previous}.ifEmpty{candidates};val next=options[rnd.nextInt(options.size)];a[blank]=a[next];a[next]=0;previous=blank;blank=next};return a}
@Composable private fun SlidePuzzle(p:PuzzleSpec.Slide,onCorrect:()->Unit){val tiles=remember(p){mutableStateListOf<Int>().also{it.addAll(scrambledTiles(p.size,p.scrambleMoves,p.seed))}};var moves by remember(p){mutableIntStateOf(0)};LazyVerticalGrid(GridCells.Fixed(p.size),Modifier.fillMaxWidth().height(310.dp),userScrollEnabled=false,horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(tiles.size){idx->val value=tiles[idx];val blank=tiles.indexOf(0);val adjacent=abs(idx/p.size-blank/p.size)+abs(idx%p.size-blank%p.size)==1;Surface(Modifier.aspectRatio(1f).clickable(enabled=value!=0&&adjacent){tiles[blank]=value;tiles[idx]=0;moves++;if(tiles.withIndex().all{(i,v)->if(i==tiles.lastIndex)v==0 else v==i+1})onCorrect()},color=if(value==0)Color.Transparent else Violet.copy(alpha=.20f),shape=RoundedCornerShape(17.dp),border=if(value==0)null else BorderStroke(1.dp,Violet.copy(alpha=.38f))){Box(contentAlignment=Alignment.Center){if(value!=0)Text(value.toString(),color=Ink,fontSize=22.sp,fontWeight=FontWeight.Black)}}}};Text("MOVES $moves",color=Muted,fontSize=11.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())}

@Composable private fun GridPathPuzzle(p:PuzzleSpec.GridPath,onAttempt:()->Unit,onCorrect:()->Unit,onWrong:()->Unit){val values=remember(p){((1..p.count).toList()+List(p.size*p.size-p.count){0}).shuffled(Random(p.seed))};var next by remember(p){mutableIntStateOf(1)};val hit=remember(p){mutableStateListOf<Int>()};LazyVerticalGrid(GridCells.Fixed(p.size),Modifier.fillMaxWidth().height(300.dp),userScrollEnabled=false,horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(values.size){idx->val v=values[idx];val done=v in hit;Surface(Modifier.aspectRatio(1f).clickable(enabled=v>0&&!done){if(v==next){hit+=v;next++;if(next>p.count)onCorrect()}else{onAttempt();onWrong()}},color=when{v==0->Color.White.copy(alpha=.025f);done->Mint.copy(alpha=.13f);else->Panel2},shape=RoundedCornerShape(15.dp),border=BorderStroke(1.dp,if(done)Mint.copy(alpha=.38f)else Color.White.copy(alpha=.07f))){Box(contentAlignment=Alignment.Center){if(v>0)Text(v.toString(),color=if(done)Mint else Ink,fontWeight=FontWeight.Black,fontSize=17.sp)}}}};Text("NEXT ${next.coerceAtMost(p.count)}",color=Blush,fontSize=12.sp,textAlign=TextAlign.Center,modifier=Modifier.fillMaxWidth())}
