package com.casezero.lastwitness;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.*;
import android.media.*;
import android.os.SystemClock;
import android.view.*;
import java.util.*;

public final class BrightGameView extends View {
    private static final int TITLE=0,SETUP=1,CASES=2,BRIEF=3,SCENE=4,CLUE=5,HUB=6,SUSPECTS=7,INTERROGATE=8,BOARD=9,TIMELINE=10,ACCUSE=11,ENDING=12,SETTINGS=13;
    private final MainActivity ctx;
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), stroke=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final ArrayList<Hit> hits=new ArrayList<>();
    private final SharedPreferences prefs;
    private final GameData.CaseFile[] cases=GameData.all();
    private int screen=TITLE,caseIndex=0,selectedEvidence=0,selectedSuspect=0,unlocked=1;
    private String detective="Detective",gender="MALE",assist="INVESTIGATOR",toast="",endingText="";
    private long toastUntil=0;
    private final HashSet<Integer> found=new HashSet<>(),examined=new HashSet<>(),boardDone=new HashSet<>();
    private int timelineProgress=0,interrogationDepth=0,trust=50,stress=20,accuseSuspect=0,accuseMotive=0,accuseMethod=0;
    private float scenePanX=0,scenePanY=0,downX,downY; private boolean dragging=false,musicOn=true,sfxOn=true,hapticsOn=true;
    private MediaPlayer ambient; private SoundPool sounds; private int sndClick,sndEvidence,sndSolved,sndFail;
    private static final class Hit{final RectF r;final String a;final int v;Hit(float l,float t,float rr,float b,String a,int v){r=new RectF(l,t,rr,b);this.a=a;this.v=v;}}

    public BrightGameView(MainActivity c){super(c);ctx=c;setFocusable(true);setLayerType(View.LAYER_TYPE_SOFTWARE,null);prefs=c.getSharedPreferences("case_zero_save",Context.MODE_PRIVATE);detective=prefs.getString("detective","Detective");gender=prefs.getString("gender","MALE");assist=prefs.getString("assist","INVESTIGATOR");unlocked=Math.max(1,prefs.getInt("unlocked",1));musicOn=prefs.getBoolean("music",true);sfxOn=prefs.getBoolean("sfx",true);hapticsOn=prefs.getBoolean("haptics",true);stroke.setStyle(Paint.Style.STROKE);initAudio();}
    private void initAudio(){try{AudioAttributes aa=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build();sounds=new SoundPool.Builder().setMaxStreams(5).setAudioAttributes(aa).build();sndClick=sounds.load(ctx,R.raw.ui_click,1);sndEvidence=sounds.load(ctx,R.raw.evidence_sting,1);sndSolved=sounds.load(ctx,R.raw.case_solved,1);sndFail=sounds.load(ctx,R.raw.soft_fail,1);ambient=MediaPlayer.create(ctx,R.raw.noir_ambient);if(ambient!=null){ambient.setLooping(true);ambient.setVolume(.22f,.22f);if(musicOn)ambient.start();}}catch(Exception ignored){}}
    public void resumeAudio(){try{if(musicOn&&ambient!=null&&!ambient.isPlaying())ambient.start();}catch(Exception ignored){}}
    public void pauseAudio(){try{if(ambient!=null&&ambient.isPlaying())ambient.pause();}catch(Exception ignored){}}
    public void setDetectiveName(String s){detective=s;prefs.edit().putString("detective",s).apply();invalidate();}

    private float d(float v){return v*getResources().getDisplayMetrics().density;} private int C(String h){return Color.parseColor(h);} private void fill(String h){p.setStyle(Paint.Style.FILL);p.setColor(C(h));}
    private void ts(float z,String h,Paint.Align a,boolean b){p.setStyle(Paint.Style.FILL);p.setTextSize(d(z));p.setColor(C(h));p.setTextAlign(a);p.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));}
    private void txt(Canvas c,String s,float x,float y,float z,String col,Paint.Align a){ts(z,col,a,false);c.drawText(s,x,y,p);} private void bold(Canvas c,String s,float x,float y,float z,String col,Paint.Align a){ts(z,col,a,true);c.drawText(s,x,y,p);}
    private void rr(Canvas c,float l,float t,float r,float b,String col,float rad){fill(col);c.drawRoundRect(l,t,r,b,d(rad),d(rad),p);} private void ol(Canvas c,float l,float t,float r,float b,String col,float rad,float w){stroke.setColor(C(col));stroke.setStrokeWidth(d(w));c.drawRoundRect(l,t,r,b,d(rad),d(rad),stroke);} private void ln(Canvas c,float x1,float y1,float x2,float y2,String col,float w){stroke.setColor(C(col));stroke.setStrokeWidth(d(w));c.drawLine(x1,y1,x2,y2,stroke);}
    private void wrap(Canvas c,String s,float x,float y,float max,float z,String col,int maxLines){ts(z,col,Paint.Align.LEFT,false);String[] ws=s.split(" ");StringBuilder line=new StringBuilder();float yy=y;int n=0;for(String w:ws){String q=line.length()==0?w:line+" "+w;if(p.measureText(q)>max&&line.length()>0){c.drawText(line.toString(),x,yy,p);yy+=d(z*1.34f);line=new StringBuilder(w);if(++n>=maxLines)return;}else line=new StringBuilder(q);}if(line.length()>0&&n<maxLines)c.drawText(line.toString(),x,yy,p);}
    private void panel(Canvas c,float l,float t,float r,float b){rr(c,l,t,r,b,"#FFF6E7",18);ol(c,l,t,r,b,"#D8C6A7",18,1);} private void button(Canvas c,String s,float l,float t,float r,float b,String a,int v,boolean primary){rr(c,l,t,r,b,primary?"#F6B73C":"#FDF5E6",13);ol(c,l,t,r,b,primary?"#D89320":"#D6C3A4",13,1);bold(c,s,(l+r)/2,(t+b)/2+d(4.5f),13,"#17324A",Paint.Align.CENTER);hits.add(new Hit(l,t,r,b,a,v));}
    private void top(Canvas c,String eye,String heading){float w=getWidth();rr(c,0,0,w,d(88),"#153B54",0);txt(c,eye.toUpperCase(Locale.US),d(20),d(33),9,"#FFD66B",Paint.Align.LEFT);bold(c,heading,d(20),d(66),22,"#FFF7E9",Paint.Align.LEFT);if(screen!=TITLE&&screen!=SETUP)button(c,"‹",w-d(60),d(22),w-d(18),d(65),"back",0,false);}
    private void backdrop(Canvas c){fill("#EAF6F4");c.drawRect(0,0,getWidth(),getHeight(),p);fill("#D7EEF2");c.drawCircle(getWidth()*.90f,getHeight()*.14f,d(145),p);fill("#FCE9B9");c.drawCircle(getWidth()*.06f,getHeight()*.83f,d(110),p);fill("#E7D8F4");c.drawCircle(getWidth()*.94f,getHeight()*.88f,d(85),p);}

    @Override protected void onDraw(Canvas c){super.onDraw(c);hits.clear();backdrop(c);switch(screen){case TITLE:drawTitle(c);break;case SETUP:drawSetup(c);break;case CASES:drawCases(c);break;case BRIEF:drawBrief(c);break;case SCENE:drawScene(c);break;case CLUE:drawClue(c);break;case HUB:drawHub(c);break;case SUSPECTS:drawSuspects(c);break;case INTERROGATE:drawInterrogate(c);break;case BOARD:drawBoard(c);break;case TIMELINE:drawTimeline(c);break;case ACCUSE:drawAccuse(c);break;case ENDING:drawEnding(c);break;case SETTINGS:drawSettings(c);break;}drawToast(c);postInvalidateDelayed(33);}

    private void drawTitle(Canvas c){float w=getWidth(),h=getHeight();txt(c,"A BRIGHT GREYBRIDGE MYSTERY",w/2,d(44),10,"#2D728F",Paint.Align.CENTER);bold(c,"CASE",w/2,d(101),39,"#173B54",Paint.Align.CENTER);bold(c,"ZERO",w/2,d(146),46,"#E86A5A",Paint.Align.CENTER);txt(c,"THE LAST WITNESS",w/2,d(174),13,"#745B46",Paint.Align.CENTER);office(c,d(18),d(194),w-d(18),Math.min(h-d(245),d(520)),true);button(c,"CONTINUE",d(32),h-d(205),w-d(32),h-d(151),"cases",0,true);button(c,"NEW INVESTIGATION",d(32),h-d(139),w-d(32),h-d(87),"setup",0,false);button(c,"SETTINGS",d(32),h-d(75),w-d(32),h-d(25),"settings",0,false);}
    private void office(Canvas c,float L,float T,float R,float B,boolean titleMode){rr(c,L,T,R,B,"#FFF4DF",24);ol(c,L,T,R,B,"#CDBA98",24,1);c.save();c.clipRect(L,T,R,B);float w=R-L,h=B-T,cx=(L+R)/2;Path f=new Path();f.moveTo(L+w*.07f,T+h*.65f);f.lineTo(cx,T+h*.39f);f.lineTo(R-w*.07f,T+h*.65f);f.lineTo(cx,T+h*.94f);f.close();fill("#D8A46A");c.drawPath(f,p);Path l=new Path();l.moveTo(L+w*.07f,T+h*.65f);l.lineTo(L+w*.07f,T+h*.16f);l.lineTo(cx,T+h*.04f);l.lineTo(cx,T+h*.39f);l.close();fill("#51B7B2");c.drawPath(l,p);Path r=new Path();r.moveTo(cx,T+h*.39f);r.lineTo(cx,T+h*.04f);r.lineTo(R-w*.07f,T+h*.17f);r.lineTo(R-w*.07f,T+h*.65f);r.close();fill("#75CAC4");c.drawPath(r,p);for(int i=0;i<7;i++)ln(c,L+w*(.14f+i*.10f),T+h*.70f,cx,T+h*.91f,"#BF8953",.6f);
        float bx=L+w*.14f,by=T+h*.17f,bw=w*.28f,bh=h*.21f;rr(c,bx,by,bx+bw,by+bh,"#E8C48D",5);ol(c,bx,by,bx+bw,by+bh,"#96643A",5,2);String[] pc={"#FFF5D6","#F7AFA1","#B8E5D8","#D3C0F2","#FFDF8D"};for(int i=0;i<5;i++){float px=bx+d(9)+(i%3)*bw*.29f,py=by+d(9)+(i/3)*bh*.43f;rr(c,px,py,px+bw*.22f,py+bh*.31f,pc[i],2);}ln(c,bx+bw*.18f,by+bh*.28f,bx+bw*.70f,by+bh*.65f,"#E86A5A",1.3f);
        float wx=L+w*.61f,wy=T+h*.14f,ww=w*.22f,wh=h*.20f;rr(c,wx,wy,wx+ww,wy+wh,"#DFF4FF",6);ol(c,wx,wy,wx+ww,wy+wh,"#FFF9ED",6,3);fill("#8BC9E7");c.drawRect(wx+d(5),wy+d(5),wx+ww-d(5),wy+wh-d(5),p);ln(c,wx+ww/2,wy+d(5),wx+ww/2,wy+wh-d(5),"#FFF8ED",2);
        Path desk=new Path();desk.moveTo(L+w*.28f,T+h*.55f);desk.lineTo(L+w*.51f,T+h*.44f);desk.lineTo(L+w*.70f,T+h*.53f);desk.lineTo(L+w*.47f,T+h*.66f);desk.close();fill("#875532");c.drawPath(desk,p);rr(c,L+w*.43f,T+h*.43f,L+w*.56f,T+h*.51f,"#274B5E",3);rr(c,L+w*.448f,T+h*.442f,L+w*.552f,T+h*.494f,"#86DCD4",2);fill("#FFE186");c.drawCircle(L+w*.34f,T+h*.47f,d(25),p);fill("#F6B73C");c.drawCircle(L+w*.34f,T+h*.47f,d(6),p);
        rr(c,L+w*.66f,T+h*.50f,L+w*.84f,T+h*.66f,"#397895",11);rr(c,L+w*.68f,T+h*.49f,L+w*.82f,T+h*.57f,"#4B91AA",10);rr(c,L+w*.69f,T+h*.53f,L+w*.735f,T+h*.585f,"#FFD66B",4);rr(c,L+w*.755f,T+h*.53f,L+w*.80f,T+h*.585f,"#F58B7C",4);Path rug=new Path();rug.moveTo(L+w*.35f,T+h*.70f);rug.lineTo(L+w*.54f,T+h*.60f);rug.lineTo(L+w*.75f,T+h*.70f);rug.lineTo(L+w*.54f,T+h*.82f);rug.close();fill("#E86A5A");c.drawPath(rug,p);plant(c,L+w*.84f,T+h*.44f,.85f);plant(c,L+w*.17f,T+h*.70f,.7f);if(!titleMode)tinyDetective(c,L+w*.54f,T+h*.72f);c.restore();}
    private void plant(Canvas c,float x,float y,float s){rr(c,x-d(8*s),y,x+d(8*s),y+d(17*s),"#C86F45",4);fill("#4F9B62");for(int i=0;i<5;i++){double a=-1.9+i*.48;float xx=x+(float)Math.cos(a)*d(12*s),yy=y-d(8*s)+(float)Math.sin(a)*d(9*s);c.drawOval(xx-d(7*s),yy-d(7*s),xx+d(7*s),yy+d(9*s),p);}}
    private void tinyDetective(Canvas c,float x,float y){fill("#EBC2A0");c.drawCircle(x,y-d(19),d(9),p);fill(gender.equals("MALE")?"#33485A":"#6B3F56");c.drawCircle(x,y-d(24),d(9),p);rr(c,x-d(11),y-d(10),x+d(11),y+d(18),"#284B63",6);ln(c,x-d(6),y+d(17),x-d(8),y+d(31),"#354A58",3);ln(c,x+d(6),y+d(17),x+d(8),y+d(31),"#354A58",3);}

    private void drawSetup(Canvas c){top(c,"PROFILE","Choose your detective");float w=getWidth(),h=getHeight();panel(c,d(20),d(106),w-d(20),d(215));txt(c,"DETECTIVE NAME",d(38),d(136),9,"#7C6F61",Paint.Align.LEFT);bold(c,detective,d(38),d(174),23,"#17324A",Paint.Align.LEFT);button(c,"EDIT NAME",w-d(128),d(128),w-d(38),d(190),"name",0,false);txt(c,"IDENTITY",d(24),d(258),9,"#2D728F",Paint.Align.LEFT);portrait(c,w*.28f,d(336),0,gender.equals("MALE"));portrait(c,w*.72f,d(336),1,gender.equals("FEMALE"));button(c,"MALE",d(24),d(405),w/2-d(7),d(458),"gender",0,gender.equals("MALE"));button(c,"FEMALE",w/2+d(7),d(405),w-d(24),d(458),"gender",1,gender.equals("FEMALE"));txt(c,"ASSISTANCE",d(24),d(500),9,"#2D728F",Paint.Align.LEFT);String[] m={"DETECTIVE","INVESTIGATOR","STORY"};for(int i=0;i<3;i++)button(c,m[i],d(24),d(516+i*56),w-d(24),d(564+i*56),"assist",i,assist.equals(m[i]));button(c,"BEGIN CASE FILE",d(24),h-d(78),w-d(24),h-d(24),"cases",0,true);}
    private void drawCases(Canvas c){top(c,"SEASON ONE","Case files");float w=getWidth(),y=d(105);for(int i=0;i<cases.length;i++){GameData.CaseFile f=cases[i];boolean open=i<unlocked;panel(c,d(18),y,w-d(18),y+d(106));thumb(c,d(28),y+d(10),d(112),y+d(96),i,open);txt(c,f.id,d(125),y+d(28),8,open?"#2D728F":"#9B958A",Paint.Align.LEFT);bold(c,f.title,d(125),y+d(54),15,open?"#17324A":"#9B958A",Paint.Align.LEFT);wrap(c,open?f.subtitle:"LOCKED — solve the previous case",d(125),y+d(76),w-d(155),10,open?"#745F4E":"#A49E93",2);if(open)hits.add(new Hit(d(18),y,w-d(18),y+d(106),"openCase",i));y+=d(116);}}
    private void thumb(Canvas c,float L,float T,float R,float B,int idx,boolean open){String[] bg={"#5CBAB5","#75B4D2","#F0A968","#D9887F","#7189B7"};rr(c,L,T,R,B,open?bg[idx%bg.length]:"#D8D3C8",8);float w=R-L,h=B-T;Path fl=new Path();fl.moveTo(L+w*.12f,T+h*.65f);fl.lineTo(L+w*.50f,T+h*.43f);fl.lineTo(L+w*.88f,T+h*.65f);fl.lineTo(L+w*.50f,T+h*.88f);fl.close();fill("#C98E55");c.drawPath(fl,p);rr(c,L+w*.24f,T+h*.36f,L+w*.42f,T+h*.56f,"#F4E6C9",2);rr(c,L+w*.56f,T+h*.40f,L+w*.73f,T+h*.58f,"#345A72",3);fill("#F6B73C");c.drawCircle(L+w*.50f,T+h*.62f,d(4),p);}
    private void drawBrief(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,f.id,f.title);float w=getWidth(),h=getHeight();thumb(c,d(22),d(108),w-d(22),d(300),caseIndex,true);panel(c,d(22),d(318),w-d(22),d(414));txt(c,"VICTIM / SUBJECT",d(38),d(346),8,"#2D728F",Paint.Align.LEFT);bold(c,f.victim,d(38),d(383),22,"#17324A",Paint.Align.LEFT);panel(c,d(22),d(430),w-d(22),h-d(102));txt(c,"INITIAL BRIEFING",d(38),d(462),9,"#E07A5F",Paint.Align.LEFT);wrap(c,f.brief,d(38),d(498),w-d(76),14,"#4D4B45",12);button(c,"ENTER CRIME SCENE",d(24),h-d(78),w-d(24),h-d(24),"scene",0,true);}

    private void drawScene(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,f.id,"Crime scene");float w=getWidth(),h=getHeight();txt(c,"DRAG TO PAN • TAP GOLD CLUES",d(20),d(104),8,"#5F7A86",Paint.Align.LEFT);float L=d(16),T=d(118),R=w-d(16),B=h-d(126);rr(c,L,T,R,B,"#FFF9EE",20);ol(c,L,T,R,B,"#D4C3A4",20,1);c.save();c.clipRect(L,T,R,B);c.translate(scenePanX,scenePanY);room(c,L,T,R,B,caseIndex);for(int i=0;i<f.evidence.length;i++){float[] q=spot(i,L,T,R,B);boolean have=found.contains(i);fill(have?"#4EA66A":"#F6B73C");c.drawCircle(q[0],q[1],d(have?6:9),p);stroke.setColor(C(have?"#D8F2E2":"#FFF2B7"));stroke.setStrokeWidth(d(2));c.drawCircle(q[0],q[1],d(14),stroke);if(!dragging)hits.add(new Hit(q[0]-d(24),q[1]-d(24),q[0]+d(24),q[1]+d(24),"clue",i));}c.restore();rr(c,d(22),h-d(111),w-d(22),h-d(86),"#173B52",9);txt(c,"EVIDENCE "+found.size()+" / "+f.evidence.length,d(34),h-d(94),9,"#FFF5D6",Paint.Align.LEFT);button(c,"DETECTIVE HUB",d(24),h-d(75),w-d(24),h-d(22),"hub",0,found.size()>=Math.min(3,f.evidence.length));}
    private void room(Canvas c,float L,float T,float R,float B,int idx){float w=R-L,h=B-T,cx=(L+R)/2;String[] a={"#5AB7B2","#76B9D4","#F2B66D","#D88A83","#778EBB"},b={"#74CBC4","#8ECDE1","#F7C98B","#E5A8A0","#91A4CD"};Path f=new Path();f.moveTo(L+w*.05f,T+h*.65f);f.lineTo(cx,T+h*.38f);f.lineTo(R-w*.05f,T+h*.65f);f.lineTo(cx,T+h*.95f);f.close();fill(idx==2?"#9BA5A5":"#D4A06A");c.drawPath(f,p);Path lw=new Path();lw.moveTo(L+w*.05f,T+h*.65f);lw.lineTo(L+w*.05f,T+h*.12f);lw.lineTo(cx,T+h*.03f);lw.lineTo(cx,T+h*.38f);lw.close();fill(a[idx%5]);c.drawPath(lw,p);Path rw=new Path();rw.moveTo(cx,T+h*.38f);rw.lineTo(cx,T+h*.03f);rw.lineTo(R-w*.05f,T+h*.13f);rw.lineTo(R-w*.05f,T+h*.65f);rw.close();fill(b[idx%5]);c.drawPath(rw,p);rr(c,L+w*.58f,T+h*.12f,L+w*.79f,T+h*.30f,"#DFF4FF",5);ol(c,L+w*.58f,T+h*.12f,L+w*.79f,T+h*.30f,"#FFF7EA",5,2);Path rug=new Path();rug.moveTo(L+w*.31f,T+h*.69f);rug.lineTo(L+w*.50f,T+h*.58f);rug.lineTo(L+w*.70f,T+h*.69f);rug.lineTo(L+w*.50f,T+h*.83f);rug.close();fill(idx==3?"#5B7CB5":"#E86A5A");c.drawPath(rug,p);if(idx==2){Path car=new Path();car.moveTo(L+w*.23f,T+h*.62f);car.lineTo(L+w*.42f,T+h*.49f);car.lineTo(L+w*.70f,T+h*.56f);car.lineTo(L+w*.56f,T+h*.72f);car.close();fill("#3E7FA0");c.drawPath(car,p);}else if(idx==3){Path bed=new Path();bed.moveTo(L+w*.20f,T+h*.57f);bed.lineTo(L+w*.42f,T+h*.45f);bed.lineTo(L+w*.69f,T+h*.57f);bed.lineTo(L+w*.45f,T+h*.72f);bed.close();fill("#F4E5CB");c.drawPath(bed,p);}else{rr(c,L+w*.65f,T+h*.49f,L+w*.84f,T+h*.65f,"#3D7895",10);rr(c,L+w*.68f,T+h*.48f,L+w*.82f,T+h*.56f,"#4D91AA",9);rr(c,L+w*.69f,T+h*.53f,L+w*.735f,T+h*.58f,"#FFD66B",4);rr(c,L+w*.76f,T+h*.53f,L+w*.805f,T+h*.58f,"#F58B7C",4);}Path desk=new Path();desk.moveTo(L+w*.20f,T+h*.50f);desk.lineTo(L+w*.38f,T+h*.41f);desk.lineTo(L+w*.55f,T+h*.48f);desk.lineTo(L+w*.36f,T+h*.59f);desk.close();fill("#815231");c.drawPath(desk,p);rr(c,L+w*.31f,T+h*.41f,L+w*.43f,T+h*.49f,"#284F63",2);rr(c,L+w*.325f,T+h*.423f,L+w*.415f,T+h*.472f,"#8FE0D7",1);plant(c,L+w*.84f,T+h*.42f,.8f);if(idx!=1&&idx!=4){fill("#394954");c.drawCircle(L+w*.53f,T+h*.73f,d(8),p);ln(c,L+w*.52f,T+h*.74f,L+w*.45f,T+h*.82f,"#394954",5);ln(c,L+w*.50f,T+h*.77f,L+w*.58f,T+h*.83f,"#394954",5);}}
    private float[] spot(int i,float L,float T,float R,float B){float[][] q={{.24f,.48f},{.53f,.73f},{.71f,.50f},{.39f,.43f},{.78f,.29f},{.32f,.67f},{.63f,.64f},{.18f,.58f},{.57f,.52f},{.82f,.70f}};float[] s=q[i%q.length];return new float[]{L+(R-L)*s[0],T+(B-T)*s[1]};}

    private void drawClue(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,"EVIDENCE","Inspect clue");float w=getWidth(),h=getHeight();String[] q=f.evidence[Math.min(selectedEvidence,f.evidence.length-1)].split("\\|",2);panel(c,d(24),d(108),w-d(24),d(420));evidenceArt(c,w/2,d(265),selectedEvidence);bold(c,q[0],d(28),d(470),23,"#17324A",Paint.Align.LEFT);txt(c,"COLLECTED EVIDENCE",d(28),d(498),9,"#E86A5A",Paint.Align.LEFT);wrap(c,q.length>1?q[1]:"Evidence recovered from the scene.",d(28),d(535),w-d(56),14,"#574E45",8);boolean ex=examined.contains(selectedEvidence);button(c,ex?"EXAMINED ✓":"EXAMINE CLOSELY",d(24),h-d(145),w-d(24),h-d(91),"examine",selectedEvidence,!ex);button(c,"BACK TO SCENE",d(24),h-d(78),w-d(24),h-d(24),"scene",0,false);}
    private void evidenceArt(Canvas c,float x,float y,int i){fill("#FFF0C7");c.drawCircle(x,y,d(112),p);String[] cols={"#E86A5A","#2D728F","#4EA66A","#F6B73C","#7C67AD"};String col=cols[i%5];if(i%5==0){fill("#F4E3C5");c.drawCircle(x,y,d(58),p);ol(c,x-d(58),y-d(58),x+d(58),y+d(58),col,58,4);ln(c,x,y,x+d(28),y-d(32),"#17324A",3);ln(c,x,y,x-d(16),y+d(38),"#17324A",3);}else if(i%5==1){rr(c,x-d(42),y-d(70),x+d(42),y+d(70),"#BFE5EE",15);ol(c,x-d(42),y-d(70),x+d(42),y+d(70),col,15,3);}else if(i%5==2){rr(c,x-d(70),y-d(48),x+d(70),y+d(48),"#FFF8E8",6);ol(c,x-d(70),y-d(48),x+d(70),y+d(48),col,6,3);for(int k=0;k<4;k++)ln(c,x-d(52),y-d(25)+k*d(17),x+d(48),y-d(25)+k*d(17),"#8C7A68",1);}else if(i%5==3){rr(c,x-d(55),y-d(78),x+d(55),y+d(78),"#294E62",12);rr(c,x-d(43),y-d(62),x+d(43),y+d(44),"#94E0D9",5);}else{fill(col);for(int k=0;k<8;k++){double a=k*Math.PI/4;c.drawCircle(x+(float)Math.cos(a)*d(48),y+(float)Math.sin(a)*d(48),d(12),p);}fill("#FFF5D6");c.drawCircle(x,y,d(30),p);}}

    private void drawHub(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,f.id,"Detective office");float w=getWidth(),h=getHeight();office(c,d(18),d(102),w-d(18),d(370),false);txt(c,"CASE PROGRESS",d(24),d(405),8,"#2D728F",Paint.Align.LEFT);float pr=(found.size()+examined.size()+boardDone.size()*2+timelineProgress)/(float)Math.max(1,f.evidence.length*2+f.deductions.length*2+f.timeline.length);rr(c,d(24),d(418),w-d(24),d(432),"#D9E7E2",7);rr(c,d(24),d(418),d(24)+(w-d(48))*Math.min(1f,pr),d(432),"#F6B73C",7);float y=d(455);button(c,"CRIME SCENE",d(22),y,w/2-d(7),y+d(52),"scene",0,false);button(c,"SUSPECTS",w/2+d(7),y,w-d(22),y+d(52),"suspects",0,examined.size()>=2);y+=d(62);button(c,"EVIDENCE BOARD",d(22),y,w/2-d(7),y+d(52),"board",0,examined.size()>=3);button(c,"TIMELINE",w/2+d(7),y,w-d(22),y+d(52),"timeline",0,boardDone.size()>=2);y+=d(62);button(c,"FINAL ACCUSATION",d(22),y,w-d(22),y+d(52),"accuse",0,timelineProgress>=Math.min(3,f.timeline.length));txt(c,"Collected "+found.size()+" • Examined "+examined.size()+" • Deductions "+boardDone.size(),w/2,h-d(23),9,"#6E746F",Paint.Align.CENTER);}
    private void drawSuspects(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,"CASE INTERVIEWS","Suspects");float w=getWidth(),y=d(108);for(int i=0;i<f.suspects.length;i++){String[] a=f.suspects[i].split("\\|",3);panel(c,d(20),y,w-d(20),y+d(116));portrait(c,d(74),y+d(57),i,false);bold(c,a[0],d(125),y+d(38),16,"#17324A",Paint.Align.LEFT);txt(c,a.length>1?a[1]:"Person of interest",d(125),y+d(62),10,"#2D728F",Paint.Align.LEFT);wrap(c,a.length>2?a[2]:"",d(125),y+d(84),w-d(155),9,"#74665A",2);hits.add(new Hit(d(20),y,w-d(20),y+d(116),"interrogate",i));y+=d(126);}}
    private void portrait(Canvas c,float x,float y,int idx,boolean selected){String[] bg={"#B9E2D9","#F7D4A3","#C9D6F0","#F1C3C0","#D6C3EB"};fill(bg[idx%5]);c.drawCircle(x,y,d(selected?44:38),p);fill("#EBC2A0");c.drawCircle(x,y-d(3),d(22),p);String[] hair={"#4A342A","#7B5436","#2E3941","#8A4A3C","#4D315E"};fill(hair[idx%5]);c.drawArc(x-d(23),y-d(28),x+d(23),y+d(8),180,180,true,p);fill("#17324A");c.drawCircle(x-d(8),y-d(2),d(2),p);c.drawCircle(x+d(8),y-d(2),d(2),p);ln(c,x-d(7),y+d(10),x+d(7),y+d(10),"#9B5F56",1);if(selected)ol(c,x-d(45),y-d(45),x+d(45),y+d(45),"#F6B73C",45,3);}
    private void drawInterrogate(Canvas c){GameData.CaseFile f=cases[caseIndex];String[] a=f.suspects[selectedSuspect].split("\\|",3);top(c,"INTERROGATION",a[0]);float w=getWidth(),h=getHeight();portrait(c,w/2,d(190),selectedSuspect,true);txt(c,"TRUST "+trust+"    STRESS "+stress,w/2,d(255),10,"#2D728F",Paint.Align.CENTER);panel(c,d(22),d(285),w-d(22),d(420));wrap(c,interrogationLine(f,selectedSuspect,interrogationDepth),d(38),d(322),w-d(76),14,"#4F463F",6);String[] q={"ASK FOR THE ALIBI","CHALLENGE THE TIMELINE","PRESENT A CLUE","STAY SILENT"};for(int i=0;i<4;i++)button(c,q[i],d(24),d(450+i*61),w-d(24),d(502+i*61),"question",i,i==2&&examined.size()>=2);if(interrogationDepth>=3)button(c,"END INTERVIEW",d(24),h-d(79),w-d(24),h-d(25),"hub",0,true);}
    private String interrogationLine(GameData.CaseFile f,int s,int depth){String n=f.suspects[s].split("\\|",2)[0];if(depth==0)return n+" watches you carefully. The room is quiet enough to hear the wall clock.";if(depth==1)return "\"I already told patrol where I was. I have nothing to hide.\"";if(depth==2)return "The answer is polished, but one detail does not fit the evidence you recovered.";return "A pause. Their eyes move toward your case folder before they answer again.";}

    private void drawBoard(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,"DEDUCTION","Evidence board");float w=getWidth(),h=getHeight();rr(c,d(18),d(104),w-d(18),h-d(92),"#D8B27D",17);ol(c,d(18),d(104),w-d(18),h-d(92),"#9A6D3D",17,2);for(int i=0;i<f.deductions.length;i++){float y=d(140+i*150);boolean done=boardDone.contains(i);String[] x=f.deductions[i].split("\\|",2);rr(c,d(38),y,w-d(38),y+d(116),done?"#DFF2E6":"#FFF7DF",10);ol(c,d(38),y,w-d(38),y+d(116),done?"#4EA66A":"#B8864F",10,1);bold(c,x[0],d(54),y+d(31),13,"#17324A",Paint.Align.LEFT);wrap(c,x.length>1?x[1]:"Connect the evidence.",d(54),y+d(56),w-d(108),10,"#6D5C4C",3);txt(c,done?"CONNECTED":"TAP TO CONNECT",w-d(54),y+d(96),8,done?"#4EA66A":"#E86A5A",Paint.Align.RIGHT);hits.add(new Hit(d(38),y,w-d(38),y+d(116),"deduction",i));}button(c,"BACK TO OFFICE",d(24),h-d(76),w-d(24),h-d(24),"hub",0,false);}
    private void drawTimeline(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,"RECONSTRUCTION","Timeline");float w=getWidth(),h=getHeight();txt(c,"Tap the events in chronological order.",d(22),d(111),10,"#5F6C70",Paint.Align.LEFT);int[] order=shuffle(f.timeline.length);float y=d(142);for(int slot=0;slot<order.length;slot++){int idx=order[slot];String[] q=f.timeline[idx].split("\\|",2);boolean done=idx<timelineProgress;panel(c,d(20),y,w-d(20),y+d(74));fill(done?"#4EA66A":"#F6B73C");c.drawCircle(d(48),y+d(37),d(10),p);bold(c,q[0],d(72),y+d(31),12,"#17324A",Paint.Align.LEFT);txt(c,q.length>1?q[1]:"",d(72),y+d(53),9,"#6C5C50",Paint.Align.LEFT);if(!done)hits.add(new Hit(d(20),y,w-d(20),y+d(74),"timelineItem",idx));y+=d(82);}button(c,"BACK TO OFFICE",d(24),h-d(76),w-d(24),h-d(24),"hub",0,false);}
    private int[] shuffle(int n){int[] x=new int[n];for(int i=0;i<n;i++)x[i]=i;if(n>2){for(int i=0;i<n;i++){int j=(i*3+2)%n;int t=x[i];x[i]=x[j];x[j]=t;}}return x;}
    private void drawAccuse(Canvas c){GameData.CaseFile f=cases[caseIndex];top(c,"FINAL DEDUCTION","Make the accusation");float w=getWidth(),h=getHeight();panel(c,d(22),d(110),w-d(22),d(235));txt(c,"WHO?",d(38),d(140),9,"#2D728F",Paint.Align.LEFT);String suspect=f.suspects[accuseSuspect%f.suspects.length].split("\\|",2)[0];bold(c,suspect,d(38),d(180),19,"#17324A",Paint.Align.LEFT);button(c,"CHANGE",w-d(125),d(145),w-d(38),d(202),"cycleSuspect",0,false);panel(c,d(22),d(252),w-d(22),d(377));txt(c,"WHY?",d(38),d(282),9,"#2D728F",Paint.Align.LEFT);wrap(c,motive(f,accuseMotive),d(38),d(324),w-d(185),12,"#17324A",3);button(c,"CHANGE",w-d(125),d(287),w-d(38),d(344),"cycleMotive",0,false);panel(c,d(22),d(394),w-d(22),d(535));txt(c,"HOW?",d(38),d(424),9,"#2D728F",Paint.Align.LEFT);wrap(c,method(f,accuseMethod),d(38),d(464),w-d(185),12,"#17324A",3);button(c,"CHANGE",w-d(125),d(430),w-d(38),d(487),"cycleMethod",0,false);button(c,"SUBMIT ACCUSATION",d(24),h-d(82),w-d(24),h-d(26),"submitAccuse",0,true);}
    private String motive(GameData.CaseFile f,int i){String[] x={f.motive,"Jealousy and personal resentment","A random confrontation"};return x[i%3];}private String method(GameData.CaseFile f,int i){String[] x={f.method,"A direct attack followed by a hurried escape","An unknown accomplice created the scene"};return x[i%3];}
    private void drawEnding(Canvas c){GameData.CaseFile f=cases[caseIndex];float w=getWidth(),h=getHeight();txt(c,"CASE CLOSED",w/2,d(55),10,"#2D728F",Paint.Align.CENTER);bold(c,endingText.startsWith("Correct")?"SOLVED":"REOPENED",w/2,d(120),40,endingText.startsWith("Correct")?"#4EA66A":"#E86A5A",Paint.Align.CENTER);office(c,d(20),d(150),w-d(20),d(420),false);panel(c,d(22),d(440),w-d(22),h-d(120));wrap(c,endingText.startsWith("Correct")?f.reveal:endingText,d(38),d(480),w-d(76),14,"#4F463F",12);button(c,caseIndex+1<cases.length?"NEXT CASE FILE":"RETURN TO CASES",d(24),h-d(88),w-d(24),h-d(32),caseIndex+1<cases.length?"nextCase":"cases",0,true);}
    private void drawSettings(Canvas c){top(c,"PREFERENCES","Settings");float w=getWidth(),h=getHeight();txt(c,"AUDIO & FEEDBACK",d(24),d(120),9,"#2D728F",Paint.Align.LEFT);button(c,"MUSIC  "+(musicOn?"ON":"OFF"),d(24),d(142),w-d(24),d(198),"toggleMusic",0,musicOn);button(c,"SFX  "+(sfxOn?"ON":"OFF"),d(24),d(214),w-d(24),d(270),"toggleSfx",0,sfxOn);button(c,"HAPTICS  "+(hapticsOn?"ON":"OFF"),d(24),d(286),w-d(24),d(342),"toggleHaptics",0,hapticsOn);panel(c,d(24),d(382),w-d(24),d(530));bold(c,"VISUAL DIRECTION",d(42),d(420),15,"#17324A",Paint.Align.LEFT);wrap(c,"Bright, colorful isometric rooms with high contrast clues and a cozy mystery tone.",d(42),d(454),w-d(84),12,"#6D5F54",5);button(c,"BACK",d(24),h-d(78),w-d(24),h-d(24),"back",0,false);}

    private void drawToast(Canvas c){if(toast.length()==0||SystemClock.uptimeMillis()>toastUntil)return;float w=getWidth(),h=getHeight();rr(c,d(28),h-d(138),w-d(28),h-d(94),"#173B52",12);bold(c,toast,w/2,h-d(110),10,"#FFF5D6",Paint.Align.CENTER);}private void toast(String s){toast=s;toastUntil=SystemClock.uptimeMillis()+1800;}private void click(){if(sfxOn&&sounds!=null)sounds.play(sndClick,.45f,.45f,1,0,1);if(hapticsOn)performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);}private void evidenceSound(){if(sfxOn&&sounds!=null)sounds.play(sndEvidence,.60f,.60f,1,0,1);}private void solvedSound(){if(sfxOn&&sounds!=null)sounds.play(sndSolved,.60f,.60f,1,0,1);}private void failSound(){if(sfxOn&&sounds!=null)sounds.play(sndFail,.45f,.45f,1,0,1);}
    @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){downX=x;downY=y;dragging=false;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE&&screen==SCENE){float dx=x-downX,dy=y-downY;if(Math.abs(dx)+Math.abs(dy)>d(8)){scenePanX+=dx;scenePanY+=dy;downX=x;downY=y;dragging=true;invalidate();}return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(dragging){dragging=false;return true;}for(int i=hits.size()-1;i>=0;i--){Hit h=hits.get(i);if(h.r.contains(x,y)){handle(h.a,h.v);return true;}}}return true;}
    private void handle(String a,int v){click();GameData.CaseFile f=cases[caseIndex];switch(a){case"setup":screen=SETUP;break;case"cases":screen=CASES;break;case"settings":screen=SETTINGS;break;case"name":ctx.promptDetectiveName(detective);break;case"gender":gender=v==0?"MALE":"FEMALE";prefs.edit().putString("gender",gender).apply();break;case"assist":String[] m={"DETECTIVE","INVESTIGATOR","STORY"};assist=m[v%3];prefs.edit().putString("assist",assist).apply();break;case"openCase":openCase(v);screen=BRIEF;break;case"scene":screen=SCENE;break;case"clue":selectedEvidence=v;found.add(v);evidenceSound();screen=CLUE;break;case"examine":examined.add(v);evidenceSound();toast("Evidence understood");break;case"hub":screen=HUB;break;case"suspects":if(examined.size()>=2)screen=SUSPECTS;else toast("Examine more evidence first");break;case"interrogate":selectedSuspect=v;interrogationDepth=0;trust=50;stress=20;screen=INTERROGATE;break;case"question":interrogationDepth++;if(v==0)trust+=5;if(v==1)stress+=12;if(v==2){stress+=7;trust-=2;}if(v==3)trust+=2;toast("Response recorded");break;case"board":if(examined.size()>=3)screen=BOARD;else toast("You need more examined evidence");break;case"deduction":if(examined.size()>=Math.min(3+v,f.evidence.length)){boardDone.add(v);solvedSound();toast("Connection made");}else{failSound();toast("Not enough evidence yet");}break;case"timeline":if(boardDone.size()>=2)screen=TIMELINE;else toast("Connect more evidence first");break;case"timelineItem":if(v==timelineProgress){timelineProgress++;solvedSound();toast("Timeline updated");}else{failSound();toast("That event does not come next");}break;case"accuse":if(timelineProgress>=Math.min(3,f.timeline.length))screen=ACCUSE;else toast("Reconstruct the timeline first");break;case"cycleSuspect":accuseSuspect=(accuseSuspect+1)%f.suspects.length;break;case"cycleMotive":accuseMotive=(accuseMotive+1)%3;break;case"cycleMethod":accuseMethod=(accuseMethod+1)%3;break;case"submitAccuse":submitAccusation();break;case"nextCase":if(caseIndex+1<cases.length){openCase(caseIndex+1);screen=BRIEF;}else screen=CASES;break;case"toggleMusic":musicOn=!musicOn;prefs.edit().putBoolean("music",musicOn).apply();if(musicOn)resumeAudio();else pauseAudio();break;case"toggleSfx":sfxOn=!sfxOn;prefs.edit().putBoolean("sfx",sfxOn).apply();break;case"toggleHaptics":hapticsOn=!hapticsOn;prefs.edit().putBoolean("haptics",hapticsOn).apply();break;case"back":goBack();break;}invalidate();}
    private void openCase(int i){caseIndex=Math.max(0,Math.min(i,cases.length-1));found.clear();examined.clear();boardDone.clear();timelineProgress=0;interrogationDepth=0;accuseSuspect=accuseMotive=accuseMethod=0;scenePanX=scenePanY=0;}
    private void submitAccusation(){GameData.CaseFile f=cases[caseIndex];String who=f.suspects[accuseSuspect].split("\\|",2)[0];boolean ok=who.equals(f.killer)&&accuseMotive==0&&accuseMethod==0;if(ok){endingText="Correct deduction. "+detective+" identified the killer, motive, and method.";unlocked=Math.max(unlocked,Math.min(cases.length,caseIndex+2));prefs.edit().putInt("unlocked",unlocked).apply();solvedSound();}else{endingText="The accusation does not fit every established fact. The file stays open, and a careful detective can try again.";failSound();}screen=ENDING;}
    private void goBack(){switch(screen){case SETUP:case CASES:case SETTINGS:screen=TITLE;break;case BRIEF:screen=CASES;break;case SCENE:screen=BRIEF;break;case CLUE:screen=SCENE;break;case HUB:screen=SCENE;break;case SUSPECTS:case BOARD:case TIMELINE:case ACCUSE:screen=HUB;break;case INTERROGATE:screen=SUSPECTS;break;case ENDING:screen=CASES;break;default:screen=TITLE;}}
}
